### ISSUE TITLE
Tracebacks

### ISSUE THREAD

**Issue by mockthebear** [MarshalX/bluesky-feed-generator#14]
I was running the server with little modifications on the data_filter (changed the condition to a regexp)

And i keep getting those tracebacks:
````
Traceback (most recent call last):
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 101, in _get_or_create
    return model(**model_data)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '3l6sj...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_firehose/client.py", line 149, in _process_message_frame
    self._on_message_callback(frame)
  File "/root/bluesky-feed-generator/server/data_stream.py", line 76, in on_message_handler
    commit = parse_subscribe_repos_message(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_firehose/firehose.py", line 58, in parse_subscribe_repos_message
    return get_or_create(message.body, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 69, in get_or_create
    raise e
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 62, in get_or_create
    model_instance = _get_or_create(model_data, model, strict=strict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 103, in _get_or_create
    raise ModelError(str(e)) from e
atproto_client.exceptions.ModelError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '3l6sj...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 101, in _get_or_create
    return model(**model_data)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '3l6sj...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_firehose/client.py", line 149, in _process_message_frame
    self._on_message_callback(frame)
  File "/root/bluesky-feed-generator/server/data_stream.py", line 76, in on_message_handler
    commit = parse_subscribe_repos_message(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_firehose/firehose.py", line 58, in parse_subscribe_repos_message
    return get_or_create(message.body, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 69, in get_or_create
    raise e
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 62, in get_or_create
    model_instance = _get_or_create(model_data, model, strict=strict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 103, in _get_or_create
    raise ModelError(str(e)) from e
atproto_client.exceptions.ModelError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '3l6sj...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 101, in _get_or_create
    return model(**model_data)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '22222...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_firehose/client.py", line 149, in _process_message_frame
    self._on_message_callback(frame)
  File "/root/bluesky-feed-generator/server/data_stream.py", line 76, in on_message_handler
    commit = parse_subscribe_repos_message(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_firehose/firehose.py", line 58, in parse_subscribe_repos_message
    return get_or_create(message.body, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 69, in get_or_create
    raise e
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 62, in get_or_create
    model_instance = _get_or_create(model_data, model, strict=strict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bluesky-feed-generator/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 103, in _get_or_create
    raise ModelError(str(e)) from e
atproto_client.exceptions.ModelError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '22222...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

**Comment by mockthebear** [comment]
Yep, i am. I cloned the repository earlier this day

![image](https://github.com/user-attachments/assets/66e6b1ab-ef30-498f-a63a-641578d318c7)

**Comment by MarshalX** [comment]
Understood. I will close this as a duplicate. You can follow progress here: https://github.com/MarshalX/atproto/issues/186
