### ISSUE TITLE
atproto_client.exceptions.BadRequestError

### ISSUE THREAD

**Issue by gemhue** [MarshalX/bluesky-feed-generator#25]
Hello!

Sorry to make another issue so soon. I went to publish my feed and I got the following error. The only parts of the code that I changed from your template were the `.env` variables and the data filtering keyword (I just changed "python" to a different word) in `data_filtering.py`. Any idea what might be causing this issue? I understand from the error that a file is too large but I tried a different keyword that I know is in very few posts and got the same error.

```py
Traceback (most recent call last):
  File "C:\lesbisky\publish_feed.py", line 82, in <module>
    main()
    ~~~~^^
  File "C:\lesbisky\publish_feed.py", line 64, in main
    response = client.com.atproto.repo.put_record(models.ComAtprotoRepoPutRecord.Data(
        repo=client.me.did,
    ...<8 lines>...
        )
    ))
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\namespaces\sync_ns.py", line 5275, in put_record
    response = self._client.invoke_procedure(
        'com.atproto.repo.putRecord',
    ...<3 lines>...
        **kwargs,
    )
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\client\base.py", line 115, in invoke_procedure
    return self._invoke(InvokeType.PROCEDURE, url=self._build_url(nsid), params=params, data=data, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\client\client.py", line 40, in _invoke
    return super()._invoke(invoke_type, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\client\base.py", line 122, in _invoke
    return self.request.post(**kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\request.py", line 165, in post
    return _parse_response(self._send_request('POST', *args, **kwargs))
                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\request.py", line 155, in _send_request
    _handle_request_errors(e)
    ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\request.py", line 54, in _handle_request_errors
    raise exception
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\request.py", line 153, in _send_request
    return _handle_response(response)
  File "C:\lesbisky\.venv\Lib\site-packages\atproto_client\request.py", line 79, in _handle_response
    raise exceptions.BadRequestError(error_response)
atproto_client.exceptions.BadRequestError: Response(success=False, status_code=400, content=XrpcError(error='BlobTooLarge', message='This file is too large. It is 1.52MB but the maximum size is 976.56KB.'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'ratelimit-limit': '5000', 'ratelimit-remaining': '4951', 'ratelimit-reset': '1735681088', 'ratelimit-policy': '5000;w=3600', 'content-type': 'application/json; charset=utf-8', 'content-length': '107', 'etag': 'W/"6b-Vq8qtGvfeL23UWbTqOff8RR5qME"', 'date': 'Tue, 31 Dec 2024 21:26:44 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})
```

**Comment by MarshalX** [comment]
Hello, you should compress your feed avatar first

> This file is too large. It is 1.52MB but the maximum size is 976.56KB.

**Comment by gemhue** [comment]
I didn't even think about the icon being the issue, I'll compress it and see it that fixes the issue! I did put the avatar `.png` file directly in the root dir and set the `AVATAR_PATH` to `'./sappho_icon.png'`.

**Comment by gemhue** [comment]
Compressing the feed avatar fixed the issue!

**Comment by MarshalX** [comment]
nice! happy new year!
